GET http://localhost:3000/books HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/books?email=phony@email.com

###
POST http://localhost:3000/books?email=phony@email.com HTTP/1.1
Content-Type: application/json

{
  "name": "Js101",
  "status": "Mint condition"
}

###
DELETE http://localhost:3000/books/5?email=phony@email.com HTTP/1.1


###
PUT http://localhost:3000/books/0 HTTP/1.1
Content-Type: application/json

{
  "email": "phony@email.com",
  "books": [{
    "name": "Something",
    "status": "Condition"
  }]
}